--
-- DERBY automatically creates an INDEX for a FK constraint, no matter if there already is an index
-- https://db.apache.org/derby/docs/10.0/manuals/reference/sqlj32.html --> Backing Indexes
-- Therefore we commented the index creation
--

CREATE TABLE "APP"."EMPLOYEE"
(
   EMAIL varchar(140) PRIMARY KEY NOT NULL,
   FIRSTNAME varchar(50) NOT NULL,
   LASTNAME varchar(50) NOT NULL,
   PASSWORD varchar(70) NOT NULL
);

CREATE TABLE "APP"."EMPLOYEE2ROLE"
(
   ID varchar(50) PRIMARY KEY NOT NULL,
   ROLENAME varchar(20) NOT NULL,
   EMPLOYEE_EMAIL varchar(140) NOT NULL
);
CREATE UNIQUE INDEX UIX_E2R_ROLE_EMAIL ON "APP"."EMPLOYEE2ROLE"(ROLENAME, EMPLOYEE_EMAIL);
-- CREATE INDEX IX_E2R_E_EMAIL ON "APP"."EMPLOYEE2ROLE"(EMPLOYEE_EMAIL);

CREATE TABLE "APP"."PROJECT"
(
   PROJECTID varchar(50) PRIMARY KEY NOT NULL,
   TITLE varchar(50) NOT NULL,
   DESCRIPTION varchar(255) NOT NULL,
   OWNER_EMAIL varchar(140) NOT NULL,
   STARTDATE date NOT NULL,
   ENDDATE date NOT NULL,
   LOCKED smallint DEFAULT 0 NOT NULL
);
-- CREATE INDEX IX_P_EMAIL ON "APP"."PROJECT"(OWNER_EMAIL);

CREATE TABLE "APP"."PROJECT2EMPLOYEE"
(
   ID varchar(50) PRIMARY KEY NOT NULL,
   EMPLOYEE_EMAIL varchar(140) NOT NULL,
   PROJECT_PROJECTID varchar(50) NOT NULL
);
CREATE UNIQUE INDEX UIX_P2E_EAMIL_PID ON "APP"."PROJECT2EMPLOYEE"(EMPLOYEE_EMAIL, PROJECT_PROJECTID);
-- CREATE INDEX IX_P2E_EMAIL ON "APP"."PROJECT2EMPLOYEE"(EMPLOYEE_EMAIL);
-- CREATE INDEX IX_P2E_PID ON "APP"."PROJECT2EMPLOYEE"(PROJECT_PROJECTID);

CREATE TABLE "APP"."TIMERECORD"
(
   ID varchar(50) PRIMARY KEY NOT NULL,
   OWNER_EMAIL varchar(140) NOT NULL,
   PROJECT_PROJECTID varchar(50) NOT NULL,
   STARTTIME timestamp NOT NULL,
   ENDTIME timestamp NOT NULL,
   PAUSEMINUTES int NOT NULL,
   RECORDSTATUS int NOT NULL
);
-- CREATE INDEX IX_TR_PID ON "APP"."TIMERECORD"(PROJECT_PROJECTID);
-- CREATE INDEX IX_TR_EMAIL ON "APP"."TIMERECORD"(OWNER_EMAIL);


ALTER TABLE "APP"."EMPLOYEE2ROLE"
ADD CONSTRAINT FK_E2R_E_EMAIL
FOREIGN KEY (EMPLOYEE_EMAIL)
REFERENCES "APP"."EMPLOYEE"(EMAIL);

ALTER TABLE "APP"."PROJECT"
ADD CONSTRAINT FK_P_E_EMAIL
FOREIGN KEY (OWNER_EMAIL)
REFERENCES "APP"."EMPLOYEE"(EMAIL);

ALTER TABLE "APP"."PROJECT2EMPLOYEE"
ADD CONSTRAINT FK_P2E_E_EMAIL
FOREIGN KEY (EMPLOYEE_EMAIL)
REFERENCES "APP"."EMPLOYEE"(EMAIL);

ALTER TABLE "APP"."PROJECT2EMPLOYEE"
ADD CONSTRAINT FK_P2E_P_PID
FOREIGN KEY (PROJECT_PROJECTID)
REFERENCES "APP"."PROJECT"(PROJECTID);

ALTER TABLE "APP"."TIMERECORD"
ADD CONSTRAINT FK_TR_E_EMAIL
FOREIGN KEY (OWNER_EMAIL)
REFERENCES "APP"."EMPLOYEE"(EMAIL);

ALTER TABLE "APP"."TIMERECORD"
ADD CONSTRAINT FK_TR_P_PID
FOREIGN KEY (PROJECT_PROJECTID)
REFERENCES "APP"."PROJECT"(PROJECTID);
