DELETE FROM "APP"."TIMERECORD" WHERE 1 = 1;
DELETE FROM "APP"."PROJECT2EMPLOYEE" WHERE 1 = 1;
DELETE FROM "APP"."PROJECT" WHERE 1 = 1;
DELETE FROM "APP"."EMPLOYEE2ROLE" WHERE 1 = 1;
DELETE FROM "APP"."EMPLOYEE" WHERE 1 = 1;
